{% set version = "1.2.2" %}
{% set name = "deap" %}
{% set sha256 = "95c63e66d755ec206c80fdb2908851c0bef420ee8651ad7be4f0578e9e909bcf" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 95c63e66d755ec206c80fdb2908851c0bef420ee8651ad7be4f0578e9e909bcf

build:
  number: 0
  script:
    - python setup.py build_ext -I${PREFIX}/include  # [unix]
    - python setup.py build_ext -I"%LIBRARY_INC%"  # [win]
    - python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - numpy >=1.5
    - pypandoc
    - python
    - setuptools
    - toolchain

  run:
    - numpy >=1.5
    - python

test:
  requires:
    - nose
    - python
  imports:
    - deap
    - deap.benchmarks
    - deap.tests
    - deap.tools
    - deap.tools._hypervolume
  commands:
    - nosetests deap.tests

about:
  home: https://github.com/deap
  license: LGPL-3.0
  license_family: LGPL
  license_file: LICENSE.txt
  summary: Distributed Evolutionary Algorithms in Python
  doc_url: https://deap.readthedocs.io
  dev_url: https://github.com/deap/deap
  description: |
    DEAP is a novel evolutionary computation framework for rapid prototyping and testing of
    ideas. It seeks to make algorithms explicit and data structures transparent. It works
    in perfect harmony with parallelisation mechanism such as multiprocessing and SCOOP. The
    following documentation presents the key concepts and many features to build your own
    evolutions.

extra:
  recipe-maintainers:
    - bollwyvl
    - rhiever
    - tonyfast
