{% set name = "deap" %}
{% set version = "1.3.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cd0fd7bccf7837b9e6a666b75e1c3a629fa3f5bc346cb90a9edd8cd56f085980

build:
  number: 0
  script:
    - {{ PYTHON }} setup.py build_ext -I{{ PREFIX }}/include  # [unix]
    - {{ PYTHON }} setup.py build_ext -I"%LIBRARY_INC%"  # [win]
    - {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - numpy
    - pypandoc
    - python
    - pip

  run:
    - numpy
    - python

test:
  requires:
    - nose
    - nose-cov
    - python
  imports:
    - deap
    - deap.benchmarks
    - deap.tests
    - deap.tools
    - deap.tools._hypervolume
  commands:
    - nosetests deap.tests --with-cov --cov deap

about:
  home: https://github.com/DEAP/deap
  license: LGPL-3.0
  license_family: LGPL
  license_file: LICENSE.txt
  summary: Distributed Evolutionary Algorithms in Python
  doc_url: https://deap.readthedocs.io
  dev_url: https://github.com/deap/deap
  doc_source_url: https://github.com/DEAP/deap/tree/master/doc
  description: |
    DEAP is a novel evolutionary computation framework for rapid prototyping and testing of
    ideas. It seeks to make algorithms explicit and data structures transparent. It works
    in perfect harmony with parallelisation mechanism such as multiprocessing and SCOOP. The
    following documentation presents the key concepts and many features to build your own
    evolutions.

extra:
  recipe-maintainers:
    - bollwyvl
    - rhiever
    - tonyfast
