# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.5
    - CONFIG=osx_python3.6

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "eZ7iuEQfj8nBi6kgOEVx0bFw3EjwSR4LDXsBmaQH7VwMtB4y3vqdJZ97/9NIabczq7ovWy0LO3skQnkCu1JpCpsKBXVMT6UFj0aIWBVYYKrKBklAxohKR1/+2DTuKF18yjWOb2awjwNo2n5rf4F822RYMY3dFniIg+9c6ktmTasmNxQnZnCCN1x5lhXVPXSE+aK1htkDfqnf0ppKJCOJl1m3LkXjGyv130fbNJaLjX9BVOL53Y7J9CyY7yimuVWgS0pUZl1ALzrEAta4OBBnq3nfA1oGFvXyV6yFpPJKerYfULL24tmBx6vSnt2HGHF9c8jmzAiL0JNB6IsWWOfBYCvC6+sVq0JBbryM1qKg6PftIKbHLiyMhEXTgLO50VYch/CiGGLLZEC7XyAPECcnMBTuSPcUsiU2hLmsVqjEN2Bi//FrwtJ5b+hi15C/EbH/lLTPiwzID6Uoz6cOhDbFVfYZbl6LRm0JX7DTIEWpgPrmluVy+eVq2fn4o8niv0Kgm3gtBh9xrEZcVnS53PTIayIkRgu29et5bQTMerGQGrIuAQsXPOBvoLQyg3r1kHWXF2Nd05cRDNFsQmPuEhvS6KRaQkBGOeZ5JzM1TIKSYZUDZ77/JUPKp9fe7kY+2GOCwSVo/OWO/bQF1hQASuK604A5wIaNP+uL/W8TQtYtcVQ="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
