# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "KI43fCdr7+cG9bf727igBg/QfMI54Rpz0n0frTvVe3liE++i6s6L4ZqnlLmDXHO/8gETiGvRTmyHaHHkOK3dJvWqTjjJc8CQuCX8c08mMMtmPfyIWjGa6Q+Sa3LyxlsqPqFffm2PFEUGBHw+pCva95wZou1mEWIaXJBujny0k7Rqx3QwlZHGjx/ua3cDVWZVf0v4slVBSJuhgqmvZdktwEse1Xe0mxqqmOAwrod4WB9eOjytfe9QpXXHjhmiGJ91K94/KzmwwZPdxHWlYJEfVc3ja2+/QZt3X6uX49rYbjcLLAL+417pYV6ae6q1QB6nZpxPYymsP7Kr9lIwyEq4Z1sr8BKWn91FejWynEvOVW5CZpWT3acQfcOoKIYH76w+ZHkyQhmAl54eqOIxV7QmaidD7ncV04xY2RNUMjdV+rOV0+RVSVWqsF2tn1YbILhQs5smZD4bxz+TSFyweBTfZy4nuT/I4jYYiXSCa7G4PMw4UunA3Mno1+6CL+nXshESlUs7xumTn/9b03eFA8MQSZxHY46z1v6Pv9L6vITyuFgUV3ZtgZNz+K/qtNvZKPh1xZfZQf7901+8u9Ptb+/IoVKk3msqwzkNk9CHBDMasWE9qxQjOC2LX011FQOeCN0mSZYdex3d/KqaBMrCqI/j925Av6arZ1OAUuSiy/cvkeQ="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
