appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: eZ7iuEQfj8nBi6kgOEVx0bFw3EjwSR4LDXsBmaQH7VwMtB4y3vqdJZ97/9NIabczq7ovWy0LO3skQnkCu1JpCpsKBXVMT6UFj0aIWBVYYKrKBklAxohKR1/+2DTuKF18yjWOb2awjwNo2n5rf4F822RYMY3dFniIg+9c6ktmTasmNxQnZnCCN1x5lhXVPXSE+aK1htkDfqnf0ppKJCOJl1m3LkXjGyv130fbNJaLjX9BVOL53Y7J9CyY7yimuVWgS0pUZl1ALzrEAta4OBBnq3nfA1oGFvXyV6yFpPJKerYfULL24tmBx6vSnt2HGHF9c8jmzAiL0JNB6IsWWOfBYCvC6+sVq0JBbryM1qKg6PftIKbHLiyMhEXTgLO50VYch/CiGGLLZEC7XyAPECcnMBTuSPcUsiU2hLmsVqjEN2Bi//FrwtJ5b+hi15C/EbH/lLTPiwzID6Uoz6cOhDbFVfYZbl6LRm0JX7DTIEWpgPrmluVy+eVq2fn4o8niv0Kgm3gtBh9xrEZcVnS53PTIayIkRgu29et5bQTMerGQGrIuAQsXPOBvoLQyg3r1kHWXF2Nd05cRDNFsQmPuEhvS6KRaQkBGOeZ5JzM1TIKSYZUDZ77/JUPKp9fe7kY+2GOCwSVo/OWO/bQF1hQASuK604A5wIaNP+uL/W8TQtYtcVQ=}
